### ISSUE TITLE
[EN][Quest][Hillsbrad Foothills] A Blight Upon the Land

### ISSUE THREAD

**Issue by Quellz** [Atlantiss/BugTracker#3999]
Upon reaching the designated area, a cutscene should trigger, but it does not. This means you can't fight the boss and get the required item, which ultimately means you can't complete the quest.

This is also part of the main questline in Hillsbrad, so it blocks you from progressing further in that area.

(main) questline in Hillsbrad - http://wow.gamepedia.com/Hillsbrad_Foothills_storyline
related: #397 - (closed)
wowhead: http://www.wowhead.com/quest=28237/a-blight-upon-the-land -

**Comment by Quellz** [comment]
Has been fixed.

**Comment by Quellz** [comment]
Welp, really hoped I wouldn't have to go back to a thread so fast.
I did the quest and it worked fine for me, but apparently, only one player can do it. This is, you complete the quest, and it's bugged again.

Screenshot of me completing the quest below.
![wowscrnshot_072915_210634](https://cloud.githubusercontent.com/assets/13531939/8968565/f2d6480a-3635-11e5-8be7-1a6a0c8d9376.jpg)

**Comment by adrians356** [comment]
I am the person who's quest is bugged. Due to this I now forever have two NPCs following me and fighting everything they see which stops me from doing things such as crafting due to me being 'in combat'

**Comment by Bildo** [comment]
Yep the event doesnt reset properly so you can complete only after a server restart. I will try to fix this by this weekend.

**Comment by SCNickNamer** [comment]
It seems like this is still an issue, can you guys if you have time take another look at this quest? Thanks

**Comment by nemusss** [comment]
can you guys please hurry up i love you server but please hurry or i will stop playing server             

I love your work so much but hurry

**Comment by HUnta1337** [comment]
its bugged plz fix

**Comment by tondiaq44** [comment]
Still not working
![wowscrnshot_101415_192652](https://cloud.githubusercontent.com/assets/15091788/10491949/948e3a54-72a9-11e5-963e-9306ab651845.jpg)

**Comment by BAndysc** [comment]
It now resets properly.
