### ISSUE TITLE
[EN] [Webpage] [Forum] Dark Theme bug

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#4753]
In the bottom left i some how clicked change theme DARK option and now i cant see the forums once i log in its just a blank white page i have no clue how to get it back plz help.

**Comment by Achiver** [comment]
I tried and I regret it , cant see forum now

**Comment by Thefakemccoy** [comment]
nope its a solid white screen

**Comment by Thefakemccoy** [comment]
the only way to see it is clear your history and dont log back in

**Comment by xolon** [comment]
rip forum

**Comment by Thefakemccoy** [comment]
This it what the screen looks like after loggin into the forums now. 
![desktop](https://cloud.githubusercontent.com/assets/12252441/10713300/6a1f6124-7a85-11e5-8a67-f8d3c0758c4f.png)

**Comment by Thefakemccoy** [comment]
Fixed thanks to Bastek.

**Comment by xolon** [comment]
Still problem for me

**Comment by Thefakemccoy** [comment]
Bastek i know can fix it

**Comment by Achiver** [comment]
Problem still for me too.
In addition after I clicked "use mobile version" on my phone, it went white too.
BTW. Don't close it as it happens to others too.

**Comment by Bildo** [comment]
well would be great if you could post your forum nicks

**Comment by xolon** [comment]
sniprep

**Comment by Achiver** [comment]
Achiever
