### ISSUE TITLE
[En][Rogue][Spell] Gouge

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#7013]
Gouge breaks from self-inflicted main gauche (combat mastery chance attack).
I'm unsure what should happen, probably it shouldn't proc from gouge at all like instant poisons. Currently it breaks gouges half the time which sucks when taking combat gouge talents into consideration.
Gouge: http://cata.openwow.com/spell=1776
Main gauche: http://cata.openwow.com/spell=86392 or http://cata.openwow.com/spell=76806 (not sure)

**Comment by kadi2** [comment]
Actually poisons don't proc from any of combat spells from spell book on the server (kick is an exception :D) Prolly Gouge should be the only exception in both cases.

**Comment by Bjarzyna** [comment]
I get a lot of poison procs from sinister strikes and revealing strikes so I'm not really sure what kind of spells you're talking about.

**Comment by kadi2** [comment]
Kidney Shot, Garrote and others that doesn't deal initial damage

**Comment by Bjarzyna** [comment]
Very nice catch.
On the side note I don't know if kidney shots should poison, doesn't seem likely. Kick poison applying may be leftover from times when kick dealth like 50 damage (TBC). Anyway good to know you have poison on your feet.

**Comment by Milton3450** [comment]
So many bugs with combat :(. Gouge, killing spree and damage calculations.s

**Comment by Milton3450** [comment]
So many bugs with combat. Gouge, Killing Spree and damage calculations.

**Comment by lamaATS** [comment]
Fixed in rev. 5208

**Comment by Bjarzyna** [comment]
Still broken in rev. 5227

**Comment by lamaATS** [comment]
What you mean by this?

**Comment by Milton3450** [comment]
Yeah I think I also noticed it's still broken. The main gauche attacks still break gouge.

**Comment by lamaATS** [comment]
Always it breaks gouge?

**Comment by Milton3450** [comment]
I haven't tested. I have just seen it during pvp.

**Comment by Bjarzyna** [comment]
If main gauche procs on gouge the gouge effect breaks (same as before).
Tested on dummies but also noticed in pvp

**Comment by lamaATS** [comment]
I have on my test server 100% change on *Main Gauche* and It's not interrupted.
Can you give me screenshot with combat log? Or If you can use /combatlog and upload somewhere log?
I'm on 99,9% sure it's another spell.

**Comment by kadi2** [comment]
@Bjarzyna Make sure you don't have deadly poison on your target, bleeds, you don't use wound poison, instant poison on your main hand.

**Comment by lamaATS** [comment]
Btw. **Poisons** should break **Gouge**

**Comment by kadi2** [comment]
@lamaATS Typed too many poisons in the last post, it should just break from Deadly Poison ticks.

**Comment by Bjarzyna** [comment]
Sorry, you're right, it's not main gauche that breaks gouge for me, it's wound poison proc from main gauche.
Gouge seem to never apply poison, however when main gauche procs it does. Damage from the skill itself doesn't break the effect, but damage from the poison does.
I still think it needs further fixing.

**Comment by kadi2** [comment]
The question is now if main gauche should have a chance to proc poisons. Gonna post some links saying it shouldn't.
http://www.mmo-champion.com/threads/906834-Main-Gauche-Mastery?p=11513299&viewfull=1#post11513299

**Comment by lamaATS** [comment]
So the problem is that **Main Gauche** can proc **Poisons** I will try to fix it soon. If someone of you can make new issue about it and put reference here.

**Comment by kadi2** [comment]
I would want to find some more sources that says it shouldn't proc poisons. There are just many sources that says it should proc it aswell.

**Comment by kadi2** [comment]
There are more sources saying that it should proc poisons, so i don't see the point in making a fix to something unsure.
http://us.battle.net/forums/en/wow/topic/2228424007
http://us.battle.net/forums/en/wow/topic/2089282319

**Comment by Milton3450** [comment]
If we think about it logically poison shouldn't proc from gouge. If it does it defeats the whole purpose of using gouge if it just breaks anyway.
