### ISSUE TITLE
[EN][Talent][Paladin] Conviction

### ISSUE THREAD

**Issue by Deryan555** [Atlantiss/BugTracker#9318]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Talent "Conviction" in holy specialisation is not working

**Current behaviour**: When I causing a crit damage of my spells and attacks, the talent has no effect

**Expected behaviour**: "Gives you a X% bonus to damage and healing for 15 sec after causing a critical effect from a weapon swing, spell, or ability. This effect stacks up to 3 times".

**Steps to reproduce the problem**:

1. Cast any healing spell or use autoattack to critically hit
2. Cast any healing spell or use autoattack to critically hit
3. Cast any healing spell or use autoattack to critically hit
![wowscrnshot_070517_224005](https://user-images.githubusercontent.com/29930568/27884067-3bbd10ba-61d3-11e7-861c-3307660c6497.jpg)
![wowscrnshot_070517_224009](https://user-images.githubusercontent.com/29930568/27884068-3bc09316-61d3-11e7-9806-ad74889d8a2f.jpg)
![wowscrnshot_070517_224014](https://user-images.githubusercontent.com/29930568/27884069-3bc557b6-61d3-11e7-92a1-b1f636161286.jpg)

**Revision**: 5451

**Comment by Piklo** [comment]
relog / respec / die

**Comment by Deryan555** [comment]
Im try everything

**Comment by Piklo** [comment]
works fine for me

**Comment by Deryan555** [comment]
Yea but its happens only with me. Im asked another paladins, and we tested. All is ok

**Comment by Piklo** [comment]
reset your spec

**Comment by Aival94** [comment]
If only happen to you try to change spec and respec back or change your glyphs to sth else and then glyph again the same.

**Comment by Deryan555** [comment]
Im try to do all of this things

**Comment by calladin** [comment]
i got same iisue, i respeced and reglyphed and convition was working until it get 3 stacks after it dissapeared it neved popped again :( @Jenovas  PLS HELP its gamebreaker in pvp permanently without 9% crit and 9% more healing done.

**Comment by Piklo** [comment]
>  its gamebreaker in pvp permanently without 9% crit

this talent doesn't increase crit :D

**Comment by calladin** [comment]
Fixed :D

**Comment by Drokal** [comment]
After 5 respecs, speccing in prot and back to holy, resetting all glyphs, about 10 deaths (all at once), checking this on my second paladin char I can say: this is bugged for me. I checked this on other client (even other computer) too, still not working.
This is really gamebreaking bug.
Idk what to do, ticket or support mail, or fck this and go play other class?

**Comment by Piklo** [comment]
Just wait for fix lol, please don't h8 xd
Posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/14843-9318-conviction-spell_proc_event/

**Comment by Piklo** [comment]
fixed in [rev5473](https://atlantiss.eu/changelog#rev5473)
